# Generated by Django 6.0.3 on 2026-03-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_track_genre_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.ManyToManyField(to='main.genre'),
        ),
    ]
